<a href="https://colab.research.google.com/github/Dhonald229/Projet-colab/blob/main/Etude_d'actif_financier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Projet D'étude d'investissement**

In [1]:
import pandas as pd

In [2]:
import yfinance as yf

In [3]:
prix=yf.Ticker("AAPL").history(period="5y")
prix

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-07-02 00:00:00-04:00,134.418268,136.465253,134.272061,136.426270,78852600,0.0,0.0
2021-07-06 00:00:00-04:00,136.533487,139.535709,136.533487,138.434250,108181800,0.0,0.0
2021-07-07 00:00:00-04:00,139.915868,141.231789,139.058097,140.919876,104911600,0.0,0.0
2021-07-08 00:00:00-04:00,138.005352,140.422732,137.118325,139.623444,105575500,0.0,0.0
2021-07-09 00:00:00-04:00,139.145828,141.972603,139.048347,141.446243,99890800,0.0,0.0
...,...,...,...,...,...,...,...
2026-06-25 00:00:00-04:00,287.399994,288.799988,273.750000,275.149994,107013700,0.0,0.0
2026-06-26 00:00:00-04:00,275.000000,285.950012,274.209991,283.779999,261775500,0.0,0.0
2026-06-29 00:00:00-04:00,286.730011,288.369995,279.850006,281.739990,66427000,0.0,0.0
2026-06-30 00:00:00-04:00,281.170013,289.940002,280.700012,289.359985,65100200,0.0,0.0
2026-07-01 00:00:00-04:00,293.440002,296.589996,289.200012,294.380005,50109500,0.0,0.0

In [4]:
prix_triés=prix.drop_duplicates().dropna()
prix_triés

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-07-02 00:00:00-04:00,134.418268,136.465253,134.272061,136.426270,78852600,0.0,0.0
2021-07-06 00:00:00-04:00,136.533487,139.535709,136.533487,138.434250,108181800,0.0,0.0
2021-07-07 00:00:00-04:00,139.915868,141.231789,139.058097,140.919876,104911600,0.0,0.0
2021-07-08 00:00:00-04:00,138.005352,140.422732,137.118325,139.623444,105575500,0.0,0.0
2021-07-09 00:00:00-04:00,139.145828,141.972603,139.048347,141.446243,99890800,0.0,0.0
...,...,...,...,...,...,...,...
2026-06-25 00:00:00-04:00,287.399994,288.799988,273.750000,275.149994,107013700,0.0,0.0
2026-06-26 00:00:00-04:00,275.000000,285.950012,274.209991,283.779999,261775500,0.0,0.0
2026-06-29 00:00:00-04:00,286.730011,288.369995,279.850006,281.739990,66427000,0.0,0.0
2026-06-30 00:00:00-04:00,281.170013,289.940002,280.700012,289.359985,65100200,0.0,0.0
2026-07-01 00:00:00-04:00,293.440002,296.589996,289.200012,294.380005,50109500,0.0,0.0

In [5]:
prix_triés.dtypes

Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends       float64
Stock Splits    float64
dtype: object

In [6]:
incohérences=prix_triés[prix_triés["Low"]>prix_triés["High"]]
incohérences

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, Dividends, Stock Splits]
Index: []

In [7]:
prix_triés_vn=prix_triés[prix_triés["Volume"]==0]
prix_triés_vn

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, Dividends, Stock Splits]
Index: []

Calcul du rendement journalier:

In [8]:
prix_triés["rendement journalier"]=prix_triés["Close"].pct_change()*100
prix_triés

,Open,High,Low,Close,Volume,Dividends,Stock Splits,rendement journalier
Date,,,,,,,,
2021-07-02 00:00:00-04:00,134.418268,136.465253,134.272061,136.426270,78852600,0.0,0.0,NaN
2021-07-06 00:00:00-04:00,136.533487,139.535709,136.533487,138.434250,108181800,0.0,0.0,1.471843
2021-07-07 00:00:00-04:00,139.915868,141.231789,139.058097,140.919876,104911600,0.0,0.0,1.795528
2021-07-08 00:00:00-04:00,138.005352,140.422732,137.118325,139.623444,105575500,0.0,0.0,-0.919978
2021-07-09 00:00:00-04:00,139.145828,141.972603,139.048347,141.446243,99890800,0.0,0.0,1.305511
...,...,...,...,...,...,...,...,...
2026-06-25 00:00:00-04:00,287.399994,288.799988,273.750000,275.149994,107013700,0.0,0.0,-6.117781
2026-06-26 00:00:00-04:00,275.000000,285.950012,274.209991,283.779999,261775500,0.0,0.0,3.136473
2026-06-29 00:00:00-04:00,286.730011,288.369995,279.850006,281.739990,66427000,0.0,0.0,-0.718870
2026-06-30 00:00:00-04:00,281.170013,289.940002,280.700012,289.359985,65100200,0.0,0.0,2.704620
2026-07-01 00:00:00-04:00,293.440002,296.589996,289.200012,294.380005,50109500,0.0,0.0,1.734870

In [9]:
pt=prix_triés
rdm_max=round(pt['rendement journalier'].max(), 2)
volume_correspondant=pt[pt['rendement journalier']==pt['rendement journalier'].max()]
print("le rendement journalier maximal est",rdm_max,"%")

le rendement journalier maximal est 15.33 %

In [10]:
ptdj=pt.tail(90)
ptdj['rendement journalier'].mean()*100

np.float64(13.23499436072732)

In [11]:
display(pt.tail(100))

,Open,High,Low,Close,Volume,Dividends,Stock Splits,rendement journalier
Date,,,,,,,,
2026-02-06 00:00:00-05:00,276.606072,280.389052,276.416422,277.604218,50453400,0.00,0.0,0.800975
2026-02-09 00:00:00-05:00,277.654198,277.943940,271.449923,274.367218,44623400,0.26,0.0,-1.166048
2026-02-10 00:00:00-05:00,274.636978,275.116517,272.688761,273.428070,34376900,0.00,0.0,-0.342296
2026-02-11 00:00:00-05:00,274.447148,279.922084,274.197378,275.246399,51931300,0.00,0.0,0.665012
2026-02-12 00:00:00-05:00,275.336333,275.466219,259.940514,261.489105,81077200,0.00,0.0,-4.998174
...,...,...,...,...,...,...,...,...
2026-06-25 00:00:00-04:00,287.399994,288.799988,273.750000,275.149994,107013700,0.00,0.0,-6.117781
2026-06-26 00:00:00-04:00,275.000000,285.950012,274.209991,283.779999,261775500,0.00,0.0,3.136473
2026-06-29 00:00:00-04:00,286.730011,288.369995,279.850006,281.739990,66427000,0.00,0.0,-0.718870
2026-06-30 00:00:00-04:00,281.170013,289.940002,280.700012,289.359985,65100200,0.00,0.0,2.704620
2026-07-01 00:00:00-04:00,293.440002,296.589996,289.200012,294.380005,50109500,0.00,0.0,1.734870

In [12]:
moyenne_rdm=pt["rendement journalier"].mean()*100
moyenne_rdm

np.float64(7.657001275195427)

In [13]:
volume_correspondant

,Open,High,Low,Close,Volume,Dividends,Stock Splits,rendement journalier
Date,,,,,,,,
2025-04-09 00:00:00-04:00,171.046258,199.55563,170.986576,197.804886,184395900,0.0,0.0,15.32887

**REMARQUE:**
Après calcul du rendement journalier de l'actif AAPL(Apple), le rendement maximal depuis le 03 Avril 2021 à nos jour est de 15,33% precisement au 09 Mars 2025 avec un volume de **184395900**.Nous obtenons en moyenne sur les **90 derniers jours** un rendement journalier de ***3,85%***.